# Generated by Django 3.0.7 on 2020-06-22 13:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agents',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=100)),
                ('last_online', models.DateTimeField()),
                ('remote_ip', models.CharField(max_length=100)),
                ('operating_system', models.CharField(max_length=100)),
                ('computer_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('last_login', models.DateTimeField()),
                ('last_login_ip', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Commands',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cmdline', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Agents')),
            ],
        ),
    ]
