# Generated by Django 3.0.7 on 2020-06-24 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_agent_session_session'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent_session',
            old_name='Session',
            new_name='session',
        ),
    ]
