# Generated by Django 3.0.7 on 2020-06-28 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200626_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent_session',
            name='protocol',
        ),
        migrations.AddField(
            model_name='agent',
            name='protocol',
            field=models.CharField(default='http', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='command',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='api.Agent'),
        ),
    ]
