# Generated by Django 3.0.7 on 2020-07-03 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200628_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
