# Generated by Django 3.0.7 on 2020-06-22 13:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=100)),
                ('last_online', models.DateTimeField(default=datetime.datetime.now)),
                ('remote_ip', models.CharField(max_length=100)),
                ('operating_system', models.CharField(max_length=100)),
                ('computer_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cmdline', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Agent')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('last_login', models.DateTimeField(default=datetime.datetime.now)),
                ('last_login_ip', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='commands',
            name='agent',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.DeleteModel(
            name='Agents',
        ),
        migrations.DeleteModel(
            name='Commands',
        ),
    ]
