# Generated by Django 3.0.7 on 2020-06-26 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200624_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='identifier',
            field=models.CharField(default='ffffffffffff', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agent',
            name='remote_ip',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login_ip',
            field=models.GenericIPAddressField(),
        ),
    ]
