# Generated by Django 3.0.7 on 2020-07-03 06:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200703_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='output',
            field=models.CharField(default='', max_length=100000),
        ),
        migrations.AlterField(
            model_name='agent',
            name='last_online',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='command',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='session',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
