# Generated by Django 3.0.7 on 2020-07-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200703_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='session_dump',
            field=models.CharField(default='', max_length=100000),
        ),
    ]
