# Generated by Django 3.0.7 on 2020-07-06 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_session_session_dump'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='output',
        ),
        migrations.RemoveField(
            model_name='session',
            name='session_dump',
        ),
        migrations.AddField(
            model_name='command',
            name='session_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Output_session',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('output', models.TextField(default='', max_length=100000)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Agent')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Session')),
            ],
        ),
    ]
